name: download_viewer
description: "A Flutter package to download and view images, PDFs, and other document formats using native or custom viewers."
version: 0.0.2
homepage: 'https://github.com/basnetjiten/download_viewer'

environment:
  sdk: '>=3.3.2 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.5.0+1

  open_filex: ^4.6.0

  path_provider: ^2.1.4

  flutter_pdfview: 1.3.2

  photo_view: 0.15.0

  path: 1.9.1

  share_plus: ^10.1.4

  open_file_manager: ^1.1.1





dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


  #generators
  build_runner: 2.4.9


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

